"""L5 -- autonomous stall escalation, and the seed ensemble.

When the run stalls, rescue it without a human. Autonomy is scored as the number of
manual interventions, so an escalation path that needs nobody is worth more than any
single modelling idea.

Three critics, each in a **fresh context**. They are given the trunk source, the data
profile and the ledger's verdicts -- and deliberately not the agent's reasoning chain,
because a reviewer who reads the reasoning agrees with it. The isolation is the part
that makes the critique worth anything.
"""
from __future__ import annotations

import hashlib
import time
from pathlib import Path

import numpy as np

from . import config as C
from . import prompts
from .agent import Agent, ProposalRejected
from .llm import LLM
from .types import Node, NodeStatus, Proposal

#: Which axis a critic's proposal is filed under when it does not name one that fits.
CRITIC_DEFAULT_AXIS = {"A": "loss", "B": "debias", "C": "sequence"}


def critic_messages(trunk: Node, ledger, role: str) -> list[dict]:
    """The critic's entire context. One user message, no history, no assistant turns.

    Everything the main agent said is absent by construction: this list is built from
    the tree and the ledger, never from the agent's conversation, and the ledger is
    rendered without the run's own hypothesis text.
    """
    trunk_code = trunk.proposal.code or Path(trunk.code_path).read_text()
    score = (
        f"primary {trunk.valid.primary:.4f} (GAUC {trunk.valid.gauc:.4f}, "
        f"nDCG@5 {trunk.valid.ndcg5:.4f})"
        if trunk.valid
        else "unscored"
    )
    body = "\n\n".join(
        [
            prompts.CRITIC_ROLES[role],
            prompts.CRITIC_TASK,
            f"## The current best script — validation {score}\n\n"
            f"```python\n{trunk_code}\n```",
            ledger.render(include_mechanisms=False),
        ]
    )
    return [{"role": "user", "content": body}]


def escalate(llm: LLM, agent: Agent, trunk: Node, ledger, console=None) -> list:
    """Run the three critics and return their usable proposals, in order A, B, C.

    A critic that fails to produce a valid proposal is dropped rather than retried:
    escalation exists because the run is already stalling, and spending the rescue
    budget arguing with one reviewer is how the rescue itself stalls.
    """
    out = []
    for role in sorted(prompts.CRITIC_ROLES)[: C.N_CRITICS]:
        try:
            response = llm.complete(agent.prefix, critic_messages(trunk, ledger, role))
            generation = agent.validate(response)
        except Exception as exc:  # noqa: BLE001 -- any failure drops the critic
            if console:
                console.warn(f"critic {role} produced nothing usable: {exc}")
            continue
        if console:
            console.ok(
                f"critic {role}: {generation.proposal.axis}/"
                f"{generation.proposal.technique} — {generation.change_summary}"
            )
        out.append((role, generation.proposal.axis, generation))
    return out


# ---------------------------------------------------------------- the ensemble


ENSEMBLE_TEMPLATE = '''\
"""Rank-average of {k} confirmed nodes: {names}.

Generated by the harness at the end of the run, and a real script like any other
candidate: it has a path, a sha256, and it re-executes standalone from disk. It is not
an in-memory average applied post hoc -- `build_submission` re-executes one stored
source, so an untracked average would have nothing to re-execute.

Averaged over ranks rather than raw scores. The constituents' outputs are not on a
common scale (a logit and a smoothed rate are not commensurable), so a raw mean would
be a weighted vote in which whichever model happened to have the widest range wins.
Ranking is invariant to any monotone transform, so rank-averaging is the version of
this that respects the metric.
"""
import argparse
import pathlib

import numpy as np

MEMBERS = {members!r}
SCORE_DIR = pathlib.Path({score_dir!r})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", required=True)
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--frac", type=float, default=1.0)
    args = ap.parse_args()

    total = None
    for name in MEMBERS:
        scores = np.load(SCORE_DIR / f"{{name}}_{{args.split}}.npy")
        order = np.argsort(np.argsort(scores, kind="stable"), kind="stable")
        normalised = order.astype(np.float64) / max(len(order) - 1, 1)
        total = normalised if total is None else total + normalised
    np.save(args.out, (total / len(MEMBERS)).astype(np.float64))


if __name__ == "__main__":
    main()
'''


def build_ensemble(loop, confirmed: list[Node], iteration: int) -> Node | None:
    """Average the top-k confirmed nodes and run the result through the normal gate.

    Only nodes that already passed the 3-seed gate are eligible. Their errors are
    partly independent, so averaging attacks the selection-noise problem directly
    rather than gambling against it -- but an ensemble of unconfirmed candidates would
    just be averaging noise, so the eligibility rule is load-bearing.
    """
    members = sorted(confirmed, key=lambda n: -n.valid.primary)[: C.ENSEMBLE_TOP_K]
    if len(members) < 2:
        return None

    score_dir = Path(loop.executor.workspace) / "_ensemble"
    score_dir.mkdir(parents=True, exist_ok=True)
    usable = []
    for node in members:
        code = node.proposal.code or Path(node.code_path).read_text()
        ok = True
        for split in ("valid", "test"):
            result = loop.executor.run(code, f"{node.node_id}_ens", split,
                                       loop.cfg.confirm_seeds[0])
            if not result.ok:
                loop.console.warn(f"{node.node_id} would not re-run on {split}; excluded")
                ok = False
                break
            np.save(score_dir / f"{node.node_id}_{split}.npy",
                    np.load(result.scores_path))
        if ok:
            usable.append(node)
    if len(usable) < 2:
        return None

    names = [n.node_id for n in usable]
    code = ENSEMBLE_TEMPLATE.format(
        k=len(names),
        names=", ".join(names),
        members=names,
        score_dir=str(score_dir),
    )
    code_path = Path(loop.outputs) / f"candidate_iter_{iteration:02d}.py"
    code_path.write_text(code)

    parent = loop.tree.trunk()
    node = Node(
        node_id=f"n{iteration:02d}",
        parent_id=parent.node_id,
        iteration=iteration,
        proposal=Proposal(
            hypothesis=(
                f"The {len(names)} confirmed nodes make partly independent errors, so "
                f"averaging their rankings should cancel some of that error: noise "
                f"falls as ~sqrt(k) while the shared signal does not. This turns "
                f"several things that each worked a little into one thing that works "
                f"slightly more, and it attacks selection noise directly rather than "
                f"gambling against it."
            ),
            axis="ensemble",
            grounding="metric",
            predicted_delta=0.002,
            code=code,
            technique="rank_average_ensemble",
        ),
        status=NodeStatus.PENDING,
        code_path=str(code_path),
        code_sha256=hashlib.sha256(code.encode()).hexdigest(),
        change_summary=f"Rank-averaged {len(names)} confirmed nodes: {', '.join(names)}",
        created_at=time.time(),
    )
    loop.tree.add(node)

    per_seed, resources = loop._run_seeds(node, code, loop.cfg.confirm_seeds)
    if not per_seed:
        loop.tree.update(node.node_id, status=NodeStatus.FAILED)
        return None
    aggregate = loop.evaluator.aggregate(per_seed)
    loop.tree.update(node.node_id, resources=resources)
    node = loop.tree.record_result(node.node_id, aggregate, per_seed)

    gate = loop.evaluator.gate(aggregate, parent.valid)
    loop.console.gate(gate)
    if gate.promote and aggregate.primary > loop.tree.trunk().valid.primary:
        loop.tree.promote(node.node_id)
    loop.ledger.record(node, gate)
    from . import logger as L

    loop.log.log(L.make_entry(node, parent, gate=gate, diff="", source="ensemble"))
    return loop.tree.get(node.node_id)
